name: Telegram Login

# 触发条件
on:
  # 每周一凌晨3点 (UTC时间)
  schedule:
    - cron: '0 3 * * 1'
  # 手动触发或通过push触发也可以运行
  push:
    branches:
      - main

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios

      - name: Run Telegram Login Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: node telegram-login.js
