name: Telegram Login

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install telethon

    - name: Run Telegram login script
      env:
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        TELEGRAM_PHONE_NUMBER: ${{ secrets.TELEGRAM_PHONE_NUMBER }}
      run: |
        python - <<EOF
        from telethon import TelegramClient
        import os
        import asyncio

        api_id = os.environ['TELEGRAM_API_ID']
        api_hash = os.environ['TELEGRAM_API_HASH']
        phone_number = os.environ['TELEGRAM_PHONE_NUMBER']

        async def main():
            client = TelegramClient('session', api_id, api_hash)
            await client.start(phone=phone_number)
            
            if await client.is_user_authorized():
                print("Successfully logged in!")
                # 在这里可以添加更多操作
            else:
                print("Login failed. Manual intervention may be required.")
            
            await client.disconnect()

        asyncio.run(main())
        EOF

    - name: Upload session file
      uses: actions/upload-artifact@v2
      with:
        name: telegram-session
        path: session.session
